
spring:
  datasource:
    url: jdbc:mariadb://turi-db.crnshyl5ky2g.us-east-1.rds.amazonaws.com:3306/turi?serverTimezone=UT
    driver-class-name: org.mariadb.jdbc.Driver
    username: vegielcl
    password: akvkenqn12
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      #use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        #temp:
          #use_jdbc_metadata_defaults: false
    generate-ddl: true
  session:
    jdbc:
      initialize-schema: always
  #main:
    #web-application-type: none


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
cloud:
  aws:
    credentials:
      access-key: AKIA6LGEKMXDY6DDVPTG
      secret-key: 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
    stack:
      auto: false
    s3:
      bucket: turi-bucket
    region:
      static: ap-northeast-2
